# springboot-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: springboot-mysql-app-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30036
  selector:
    app: springboot-mysql-app
