# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env :
  PROJECT_ID : ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER : cluster-demo1
  GKE_ZONE : us-central1-c

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id : docker.io
        server-username : MAVEN_USERNAME
        server-password : MAVEN_PASSWORD
    
    - name: Building and pushing Order
      run : mvn package dockerfile:push --file ./pom.xml
    env :
          MAVEN_USERNAME : ${{secrets.DOCKER_USERNAME}}
          MAVEN_PASSWORD : ${{secrets.DOCKER_PASSWORD}}

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: kubectl - Google Cloud GKE cluster.
      uses: ameydev/gke-kubectl-action@master
      env:
        PROJECT_ID: ${{ env.PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GKA_SA_KEY }}
        CLUSTER_NAME: ${{ env.GKE_CLUSTER }}
        ZONE_NAME: ${{ env.GKE_ZONE }}
      with :
        args : apply -f k8/


 
