name: Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-demo1
  GKE_ZONE: us-central1-c

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: docker.io
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Building and pushing Order
      run: mvn package dockerfile:push --file ./pom.xml
      env:
        MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GKA_SA_KEY }}

    - name: Authenticate to Google Cloud
      env:
        GKA_SA_KEY: ${{ secrets.GKA_SA_KEY }}
      run: |
        echo $GKA_SA_KEY | base64 --decode > /tmp/account.json
        gcloud auth activate-service-account --key-file=/tmp/account.json

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}
        kubectl config set-context $(kubectl config current-context) --namespace=default

    - name: Deploy to GKE
      run: kubectl apply -f k8/
